#!/usr/bin/env python3

"""
Figure 1. Abundance of AMG-carrying viral genomes across baseline
and pre-treatment alpine lake samples.

Panel A:
    Total viral community RPKM split between AMG-carrying and
    non-AMG-carrying viral genomes.

Panel B:
    AMG-carrying viral genome RPKM divided among KEGG metabolic
    categories.

Abundance is based on the 75% breadth-of-coverage filtered RPKM
matrix generated by scripts/04_calculate_rpkm_breadth.py.

VIBRANT fragment names are resolved to their parent genome names.
Each KO is counted once per resolved genome. For genomes carrying
AMGs from multiple metabolic categories, genome RPKM is allocated
among categories in proportion to the number of unique AMG KOs in
each category.

This script is adapted from the original dissertation Figure 8
generation script.

Author: Shari Larsen
"""

from pathlib import Path
import re

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


# ---------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------

RPKM_PATH = Path(
    "results/read_recruitment/rpkm_filtered/"
    "rpkm_matrix_breadth75.tsv"
)

AMG_IND_PATH = Path(
    "results/vibrant_amg/"
    "VIBRANT_derep95_all17/"
    "VIBRANT_results_derep95_all17/"
    "VIBRANT_AMG_individuals_derep95_all17.tsv"
)

AMG_PATH_PATH = Path(
    "results/vibrant_amg/"
    "VIBRANT_derep95_all17/"
    "VIBRANT_results_derep95_all17/"
    "VIBRANT_AMG_pathways_derep95_all17.tsv"
)

OUTDIR = Path("results/figures")
OUTDIR.mkdir(parents=True, exist_ok=True)

OUT_PNG = OUTDIR / "figure1_amg_abundance.png"
OUT_SVG = OUTDIR / "figure1_amg_abundance.svg"


# ---------------------------------------------------------------------
# Load data
# ---------------------------------------------------------------------

rpkm = pd.read_csv(
    RPKM_PATH,
    sep="\t",
    index_col=0,
)

amg_ind = pd.read_csv(
    AMG_IND_PATH,
    sep="\t",
)

amg_path = pd.read_csv(
    AMG_PATH_PATH,
    sep="\t",
)


# ---------------------------------------------------------------------
# Resolve VIBRANT fragment names
# ---------------------------------------------------------------------

def resolve_genome_name(name):
    """
    Resolve VIBRANT fragment names to their parent genome.

    Example:
        genome||full_fragment_2
    becomes:
        genome||full
    """
    return re.sub(
        r"_fragment_\d+$",
        "",
        str(name),
    )


amg_ind["genome_resolved"] = (
    amg_ind["scaffold"]
    .apply(resolve_genome_name)
)


# ---------------------------------------------------------------------
# Assign AMG KOs to KEGG metabolic categories
# ---------------------------------------------------------------------

ko_to_cat = {}

for _, row in amg_path.iterrows():

    category = row["Metabolism"]

    kos = str(
        row["Present AMG KOs"]
    ).split(",")

    for ko in kos:

        ko = ko.strip()

        if ko and ko != "nan":
            ko_to_cat[ko] = category


amg_ind["category"] = (
    amg_ind["AMG KO"]
    .map(ko_to_cat)
    .fillna("Other")
)


# ---------------------------------------------------------------------
# Deduplicate AMG calls
# ---------------------------------------------------------------------

# Each KO is counted once per resolved viral genome.
# This prevents duplicate AMG calls from VIBRANT fragments of the
# same parent genome from being counted multiple times.

amg_dedup = (
    amg_ind
    .drop_duplicates(
        subset=[
            "genome_resolved",
            "AMG KO",
        ]
    )[
        [
            "genome_resolved",
            "AMG KO",
            "category",
        ]
    ]
)


# ---------------------------------------------------------------------
# Determine fractional category contribution for each genome
# ---------------------------------------------------------------------

genome_cat_counts = (
    amg_dedup
    .groupby(
        [
            "genome_resolved",
            "category",
        ]
    )
    .size()
    .reset_index(name="count")
)

genome_totals = (
    genome_cat_counts
    .groupby("genome_resolved")["count"]
    .sum()
)

genome_cat_counts["fraction"] = (
    genome_cat_counts.apply(
        lambda row:
        row["count"]
        / genome_totals[
            row["genome_resolved"]
        ],
        axis=1,
    )
)


categories = sorted(
    amg_dedup["category"].unique()
)

amg_genomes_resolved = set(
    genome_cat_counts[
        "genome_resolved"
    ].unique()
)


# ---------------------------------------------------------------------
# Samples shown in Figure 1
# ---------------------------------------------------------------------

sample_order = [
    "SRR5830790",
    "SRR5830789",
    "SRR12462965",
    "Y153",
    "SRR12462971",
    "Y16_292_L2_t0",
    "Y16_177_UC1_t0",
]

sample_labels = [
    "Elizabeth\nBaseline",
    "Lower Cathedral\nBaseline",
    "Lower Gaylor\nLG2 T0",
    "Lower Gaylor\nLG3 T0",
    "Lukens\nL6 T0",
    "Lukens\nL2 T0",
    "Upper Cathedral\nUC1 T0",
]


# ---------------------------------------------------------------------
# Calculate AMG RPKM by metabolic category
# ---------------------------------------------------------------------

cat_rpkm = {
    category: np.zeros(
        len(sample_order)
    )
    for category in categories
}


for genome, group in genome_cat_counts.groupby(
    "genome_resolved"
):

    if genome not in rpkm.index:
        continue

    genome_rpkm = (
        rpkm.loc[
            genome,
            sample_order,
        ]
        .values
    )

    for _, row in group.iterrows():

        cat_rpkm[
            row["category"]
        ] += (
            genome_rpkm
            * row["fraction"]
        )


# ---------------------------------------------------------------------
# AMG versus non-AMG abundance
# ---------------------------------------------------------------------

amg_mask = rpkm.index.isin(
    amg_genomes_resolved
)

total_rpkm = (
    rpkm[sample_order]
    .sum(axis=0)
    .values
)

amg_rpkm = (
    rpkm.loc[
        amg_mask,
        sample_order,
    ]
    .sum(axis=0)
    .values
)

non_amg_rpkm = (
    total_rpkm - amg_rpkm
)


# ---------------------------------------------------------------------
# Sanity check
# ---------------------------------------------------------------------

print(
    "=== AMG RPKM vs category sums ==="
)

print(
    f"{'Sample':<30}"
    f"{'AMG RPKM':>12}"
    f"{'Category sum':>15}"
    f"{'Difference':>12}"
)

for i, label in enumerate(
    sample_labels
):

    category_sum = sum(
        cat_rpkm[category][i]
        for category in categories
    )

    difference = (
        amg_rpkm[i]
        - category_sum
    )

    print(
        f"{label.replace(chr(10), ' '):<30}"
        f"{amg_rpkm[i]:>12.1f}"
        f"{category_sum:>15.1f}"
        f"{difference:>12.1f}"
    )


# ---------------------------------------------------------------------
# Plot colors
# ---------------------------------------------------------------------

colors = {
    "Amino acid metabolism":
        "#59a14f",

    "Biosynthesis of other secondary metabolites":
        "#ff7f0e",

    "Carbohydrate metabolism":
        "#4e79a7",

    "Energy metabolism":
        "#ff9da7",

    "Folding, sorting and degradation":
        "#bcbd22",

    "Glycan biosynthesis and metabolism":
        "#e15759",

    "Lipid metabolism":
        "#edc948",

    "Metabolism of cofactors and vitamins":
        "#f28e2b",

    "Metabolism of other amino acids":
        "#17becf",

    "Metabolism of terpenoids and polyketides":
        "#76b7b2",

    "Nucleotide metabolism":
        "#b07aa1",

    "Xenobiotics biodegradation and metabolism":
        "#8c564b",

    "Other":
        "#9c755f",

    "Non-AMG":
        "#d3d3d3",

    "AMG-carrying":
        "#2c7bb6",
}


# ---------------------------------------------------------------------
# Create figure
# ---------------------------------------------------------------------

fig, (ax1, ax2) = plt.subplots(
    2,
    1,
    figsize=(12, 11),
    gridspec_kw={
        "height_ratios": [
            1.2,
            1,
        ]
    },
)

fig.subplots_adjust(
    left=0.10,
    right=0.70,
    top=0.93,
    bottom=0.12,
    hspace=0.45,
)

x = np.arange(
    len(sample_order)
)


# ---------------------------------------------------------------------
# Panel A
# ---------------------------------------------------------------------

ax1.bar(
    x,
    non_amg_rpkm,
    label="Non-AMG-carrying",
    color=colors["Non-AMG"],
    width=0.6,
)

ax1.bar(
    x,
    amg_rpkm,
    bottom=non_amg_rpkm,
    label="AMG-carrying",
    color=colors["AMG-carrying"],
    width=0.6,
)

ax1.axvline(
    x=1.5,
    color="black",
    linewidth=1.0,
    linestyle="--",
    alpha=0.5,
)

ax1.set_xticks(x)

ax1.set_xticklabels(
    sample_labels,
    fontsize=9,
)

ax1.set_ylabel(
    "Total viral community\n"
    "abundance (RPKM)",
    fontsize=10,
)

ax1.set_title(
    "A. Total viral community RPKM: "
    "AMG-carrying vs. non-AMG-carrying genomes",
    fontsize=10,
    loc="left",
)

ax1.legend(
    bbox_to_anchor=(1.02, 1),
    loc="upper left",
    fontsize=9,
    frameon=False,
)

ymax1 = (
    total_rpkm.max()
    * 1.08
)

ax1.set_ylim(
    0,
    ymax1,
)

ax1.text(
    0.5,
    ymax1 * 0.97,
    "Baseline",
    ha="center",
    va="top",
    fontsize=9,
    style="italic",
)

ax1.text(
    4.0,
    ymax1 * 0.97,
    "Experimental lakes (T0)",
    ha="center",
    va="top",
    fontsize=9,
    style="italic",
)


# ---------------------------------------------------------------------
# Panel B
# ---------------------------------------------------------------------

bottom = np.zeros(
    len(sample_order)
)

for category in categories:

    values = cat_rpkm[
        category
    ]

    if values.sum() > 0:

        ax2.bar(
            x,
            values,
            bottom=bottom,
            label=category,
            color=colors.get(
                category,
                "#333333",
            ),
            width=0.6,
        )

        bottom += values


ax2.axvline(
    x=1.5,
    color="black",
    linewidth=1.0,
    linestyle="--",
    alpha=0.5,
)

ax2.set_xticks(x)

ax2.set_xticklabels(
    sample_labels,
    fontsize=9,
)

ax2.set_ylabel(
    "AMG-carrying viral genome\n"
    "abundance (RPKM)",
    fontsize=10,
)

ax2.set_title(
    "B. AMG-carrying genome abundance "
    "by metabolic category",
    fontsize=10,
    loc="left",
)

ax2.legend(
    bbox_to_anchor=(1.02, 1),
    loc="upper left",
    fontsize=8,
    frameon=False,
)

ymax2 = (
    bottom.max()
    * 1.08
)

ax2.set_ylim(
    0,
    ymax2,
)

ax2.text(
    0.5,
    ymax2 * 0.97,
    "Baseline",
    ha="center",
    va="top",
    fontsize=9,
    style="italic",
)

ax2.text(
    4.0,
    ymax2 * 0.97,
    "Experimental lakes (T0)",
    ha="center",
    va="top",
    fontsize=9,
    style="italic",
)


# ---------------------------------------------------------------------
# Save
# ---------------------------------------------------------------------

plt.savefig(
    OUT_PNG,
    dpi=300,
    bbox_inches="tight",
)

plt.savefig(
    OUT_SVG,
    bbox_inches="tight",
)

plt.close()

print(
    f"\nSaved: {OUT_PNG}"
)

print(
    f"Saved: {OUT_SVG}"
)
